export const CITIES = [
  // Active Cities (7)
  { id: 'Istanbul', name: 'İstanbul', region: 'Marmara', status: 'active', desc: 'Kıtaların Buluşma Noktası' },
  { id: 'Kocaeli', name: 'Kocaeli', region: 'Marmara', status: 'active', desc: 'Sanayinin Merkezi' },
  { id: 'Sakarya', name: 'Sakarya', region: 'Marmara', status: 'active', desc: 'Doğanın Kalbi' },
  { id: 'Izmir', name: 'İzmir', region: 'Ege', status: 'active', desc: "Ege'nin İncisi" },
  { id: 'Balikesir', name: 'Balıkesir', region: 'Ege', status: 'active', desc: 'Zeytin Kokulu Kent' },
  { id: 'Samsun', name: 'Samsun', region: 'Karadeniz', status: 'active', desc: "Karadeniz'in Kapısı" },
  { id: 'Antalya', name: 'Antalya', region: 'Akdeniz', status: 'active', desc: "Akdeniz'in İncisi" },

  // 74 Inactive Cities (Yakında Gelecek)
  { id: 'Adana', name: 'Adana', region: 'Akdeniz', status: 'coming_soon', desc: 'Torosların Eteğinde' },
  { id: 'Adiyaman', name: 'Adıyaman', region: 'Güneydoğu', status: 'coming_soon', desc: 'Nemrut Dağı Diyarı' },
  { id: 'Afyon', name: 'Afyonkarahisar', region: 'Ege', status: 'coming_soon', desc: 'Termal Başkent' },
  { id: 'Agri', name: 'Ağrı', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Ağrı Dağı Eteği' },
  { id: 'Amasya', name: 'Amasya', region: 'Karadeniz', status: 'coming_soon', desc: 'Şehzadeler Şehri' },
  { id: 'Ankara', name: 'Ankara', region: 'İç Anadolu', status: 'coming_soon', desc: 'Başkent' },
  { id: 'Artvin', name: 'Artvin', region: 'Karadeniz', status: 'coming_soon', desc: 'Yeşilin Her Tonu' },
  { id: 'Aydin', name: 'Aydın', region: 'Ege', status: 'coming_soon', desc: 'Efe Şehri' },
  { id: 'Bilecik', name: 'Bilecik', region: 'Marmara', status: 'coming_soon', desc: 'Kuruluşun Şehri' },
  { id: 'Bingol', name: 'Bingöl', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Yüzen Adalar' },
  { id: 'Bitlis', name: 'Bitlis', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Tarihi Yapılar Kenti' },
  { id: 'Bolu', name: 'Bolu', region: 'Karadeniz', status: 'coming_soon', desc: 'Abant & Yedi Göller' },
  { id: 'Burdur', name: 'Burdur', region: 'Akdeniz', status: 'coming_soon', desc: 'Salda Gölü Diyarı' },
  { id: 'Bursa', name: 'Bursa', region: 'Marmara', status: 'coming_soon', desc: 'Yeşil Bursa' },
  { id: 'Canakkale', name: 'Çanakkale', region: 'Marmara', status: 'coming_soon', desc: 'Tarihin Yazıldığı Yer' },
  { id: 'Cankiri', name: 'Çankırı', region: 'İç Anadolu', status: 'coming_soon', desc: 'Tuz Mağarası Kenti' },
  { id: 'Corum', name: 'Çorum', region: 'Karadeniz', status: 'coming_soon', desc: 'Hattuşaş Şehri' },
  { id: 'Denizli', name: 'Denizli', region: 'Ege', status: 'coming_soon', desc: 'Pamukkale Diyarı' },
  { id: 'Diyarbakir', name: 'Diyarbakır', region: 'Güneydoğu', status: 'coming_soon', desc: 'Tarihi Surlar Kenti' },
  { id: 'Edirne', name: 'Edirne', region: 'Marmara', status: 'coming_soon', desc: 'Serhat Şehri' },
  { id: 'Elazig', name: 'Elazığ', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Harput Diyarı' },
  { id: 'Erzincan', name: 'Erzincan', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Munzur Eteğinde' },
  { id: 'Erzurum', name: 'Erzurum', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Palandöken Diyarı' },
  { id: 'Eskisehir', name: 'Eskişehir', region: 'İç Anadolu', status: 'coming_soon', desc: 'Kültür & Gençlik Kenti' },
  { id: 'Gaziantep', name: 'Gaziantep', region: 'Güneydoğu', status: 'coming_soon', desc: 'Güneydoğunun İncisi' },
  { id: 'Giresun', name: 'Giresun', region: 'Karadeniz', status: 'coming_soon', desc: 'Fındığın Başkenti' },
  { id: 'Gumushane', name: 'Gümüşhane', region: 'Karadeniz', status: 'coming_soon', desc: 'Karaca Mağarası Kenti' },
  { id: 'Hakkari', name: 'Hakkari', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Sümbül Dağı Eteği' },
  { id: 'Hatay', name: 'Hatay', region: 'Akdeniz', status: 'coming_soon', desc: 'Medeniyetler Şehri' },
  { id: 'Isparta', name: 'Isparta', region: 'Akdeniz', status: 'coming_soon', desc: 'Gül & Lavanta Diyarı' },
  { id: 'Mersin', name: 'Mersin', region: 'Akdeniz', status: 'coming_soon', desc: 'Akdeniz Liman Kenti' },
  { id: 'Kars', name: 'Kars', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Ani Harabeleri Kenti' },
  { id: 'Kastamonu', name: 'Kastamonu', region: 'Karadeniz', status: 'coming_soon', desc: 'Ilgaz Dağı Eteği' },
  { id: 'Kayseri', name: 'Kayseri', region: 'İç Anadolu', status: 'coming_soon', desc: "Erciyes'in Gölgesinde" },
  { id: 'Kirklareli', name: 'Kırklareli', region: 'Marmara', status: 'coming_soon', desc: "Trakya'nın Yeşili" },
  { id: 'Kirsehir', name: 'Kırşehir', region: 'İç Anadolu', status: 'coming_soon', desc: 'Ahiler Şehri' },
  { id: 'Konya', name: 'Konya', region: 'İç Anadolu', status: 'coming_soon', desc: 'Huzur & Mevlana Şehri' },
  { id: 'Kutahya', name: 'Kütahya', region: 'Ege', status: 'coming_soon', desc: 'Çini Şehri' },
  { id: 'Malatya', name: 'Malatya', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Kayısının Başkenti' },
  { id: 'Manisa', name: 'Manisa', region: 'Ege', status: 'coming_soon', desc: 'Spil Dağı Eteği' },
  { id: 'Kahramanmaras', name: 'Kahramanmaraş', region: 'Akdeniz', status: 'coming_soon', desc: "Akdeniz'in Kapısı" },
  { id: 'Mardin', name: 'Mardin', region: 'Güneydoğu', status: 'coming_soon', desc: 'Tarihi Taş Konaklar' },
  { id: 'Bodrum', name: 'Bodrum / Muğla', region: 'Ege', status: 'coming_soon', desc: 'Tatil Beldeleri' },
  { id: 'Mus', name: 'Muş', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Muş Ovası Kenti' },
  { id: 'Nevsehir', name: 'Nevşehir', region: 'İç Anadolu', status: 'coming_soon', desc: 'Kapadokya Diyarı' },
  { id: 'Nigde', name: 'Niğde', region: 'İç Anadolu', status: 'coming_soon', desc: 'Aladağlar Eteği' },
  { id: 'Ordu', name: 'Ordu', region: 'Karadeniz', status: 'coming_soon', desc: 'Boztepe Şehri' },
  { id: 'Rize', name: 'Rize', region: 'Karadeniz', status: 'coming_soon', desc: 'Çayın Başkenti' },
  { id: 'Siirt', name: 'Siirt', region: 'Güneydoğu', status: 'coming_soon', desc: 'Veysel Karani Diyarı' },
  { id: 'Sinop', name: 'Sinop', region: 'Karadeniz', status: 'coming_soon', desc: "Türkiye'nin Kuzey Ucu" },
  { id: 'Sivas', name: 'Sivas', region: 'İç Anadolu', status: 'coming_soon', desc: 'Selçuklu Kenti' },
  { id: 'Tekirdag', name: 'Tekirdağ', region: 'Marmara', status: 'coming_soon', desc: 'Marmara Kıyısı' },
  { id: 'Tokat', name: 'Tokat', region: 'Karadeniz', status: 'coming_soon', desc: 'Ballıca Mağarası Diyarı' },
  { id: 'Trabzon', name: 'Trabzon', region: 'Karadeniz', status: 'coming_soon', desc: "Karadeniz'in Fırtınası" },
  { id: 'Tunceli', name: 'Tunceli', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Munzur Vadisi Kenti' },
  { id: 'Sanliurfa', name: 'Şanlıurfa', region: 'Güneydoğu', status: 'coming_soon', desc: 'Göbeklitepe Şehri' },
  { id: 'Usak', name: 'Uşak', region: 'Ege', status: 'coming_soon', desc: 'Kanyonlar Şehri' },
  { id: 'Van', name: 'Van', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Van Gölü Diyarı' },
  { id: 'Yozgat', name: 'Yozgat', region: 'İç Anadolu', status: 'coming_soon', desc: 'Çamlık Milli Parkı' },
  { id: 'Zonguldak', name: 'Zonguldak', region: 'Karadeniz', status: 'coming_soon', desc: 'Emeğin Başkenti' },
  { id: 'Aksaray', name: 'Aksaray', region: 'İç Anadolu', status: 'coming_soon', desc: 'Ihlara Vadisi Diyarı' },
  { id: 'Bayburt', name: 'Bayburt', region: 'Karadeniz', status: 'coming_soon', desc: 'Çoruh Nehrinin Kenti' },
  { id: 'Karaman', name: 'Karaman', region: 'İç Anadolu', status: 'coming_soon', desc: 'Türkçenin Başkenti' },
  { id: 'Kirikkale', name: 'Kırıkkale', region: 'İç Anadolu', status: 'coming_soon', desc: 'Kızılırmak Kenti' },
  { id: 'Batman', name: 'Batman', region: 'Güneydoğu', status: 'coming_soon', desc: 'Hasankeyf Diyarı' },
  { id: 'Sirnak', name: 'Şırnak', region: 'Güneydoğu', status: 'coming_soon', desc: 'Cudi Dağı Eteği' },
  { id: 'Bartin', name: 'Bartın', region: 'Karadeniz', status: 'coming_soon', desc: 'Amasra & Karadeniz' },
  { id: 'Ardahan', name: 'Ardahan', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Çıldır Gölü Diyarı' },
  { id: 'Igdir', name: 'Iğdır', region: 'Doğu Anadolu', status: 'coming_soon', desc: 'Doğunun Yükselen Yıldızı' },
  { id: 'Yalova', name: 'Yalova', region: 'Marmara', status: 'coming_soon', desc: 'Termal Şehir' },
  { id: 'Karabuk', name: 'Karabük', region: 'Karadeniz', status: 'coming_soon', desc: 'Safranbolu Diyarı' },
  { id: 'Kilis', name: 'Kilis', region: 'Güneydoğu', status: 'coming_soon', desc: 'Zeytin Diyarı' },
  { id: 'Osmaniye', name: 'Osmaniye', region: 'Akdeniz', status: 'coming_soon', desc: 'Fıstığın Başkenti' },
  { id: 'Duzce', name: 'Düzce', region: 'Karadeniz', status: 'coming_soon', desc: 'Samandere Şelalesi Kenti' }
];

export const SERVICES = [
  { id: 'standart', title: 'Standart Ev Temizliği', basePrice: 1500, icon: 'home', desc: 'Salon, yatak odaları, mutfak ve banyonun detaylı hijyeni.' },
  { id: 'derin', title: 'Derin Hijyenik Temizlik', basePrice: 2200, icon: 'sparkles', desc: 'Detaylı dip-köşe Dezenfeksiyon ve ekstra hijyen bakımı.' },
  { id: 'insaat', title: 'İnşaat / Tadilat Sonrası', basePrice: 3200, icon: 'building', desc: 'Tadilat kalıntıları, harç ve boya lekelerinin temizliği.' },
  { id: 'ofis', title: 'Ofis & Kurumsal Temizlik', basePrice: 2500, icon: 'briefcase', desc: 'İş yerleri, masa düzeni ve plaza ortak alan hijyeni.' },
  { id: 'villa', title: 'Villa & Rezidans Bakımı', basePrice: 4500, icon: 'shield-check', desc: 'Geniş m² konutlar, teras ve bahçe katı özel temizliği.' }
];

export const EXTRAS = [
  { id: 'cam', title: 'Dış Cam Silme', price: 350, icon: 'sun' },
  { id: 'balkon', title: 'Balkon Yıkama', price: 250, icon: 'wind' },
  { id: 'buzdolabi', title: 'Buzdolabı İçi Temizliği', price: 200, icon: 'box' },
  { id: 'firin', title: 'Fırın İçi Dezenfeksiyon', price: 200, icon: 'flame' },
  { id: 'utu', title: 'Ütü Hizmeti (1 Saat)', price: 300, icon: 'shirt' }
];
